### ISSUE TITLE
Device preference warning

### ISSUE THREAD

**Issue by ccquiel** [facebook/facebook-python-business-sdk#237]
Hi, 
I'm not really sure that this is an issue but I just upgraded to v2.7 and I've been getting the warning:

> UserWarning: Value of device_platforms is not be compatible. 
> Expect DevicePlatforms; got <class 'list'>

Checking the validation (`_field_types`) in facebook-python-ads-sdk/facebookads/adobjects/targeting.py I noticed that for this attribute it says: `'device_platforms': 'DevicePlatforms'`. Which I guess references to the subclass DevicePlatforms, but the attribute has one or two values, shouldn't it be a list like:  `'device_platforms': 'list<DevicePlatforms>'`

Cheers
Ezequiel

**Comment by rituparnamukherjee** [comment]
cc @JiamingFB

**Comment by daphyFB** [comment]
Thanks for reporting. We really appreciate it.

We opened an internal task to track this issue. However, since we're under an internal clean-up of SDK generation, the ultimate fix will take some time. We'll update you when it's done.

In the mean time, please patch it in your side. Thanks for understanding!

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
