### ISSUE TITLE
Amount of data exceeded in a small call

### ISSUE THREAD

**Issue by luklss** [facebook/facebook-python-business-sdk#470]
I just updated the SDK to 3.0 and have been getting the following error message in my priory working script: 

```bash
Status:  500
  Response:
    {
      "error": {
        "message": "Please reduce the amount of data you're asking for, then retry your request",
        "code": 1
      }
    }
```
I have since been trying to reduce the call size, but it fails even by requesting only campaign id, date and spend for one day as below:

```bash
 Method:  GET
  Path:    https://graph.facebook.com/v3.0/"MY_ACCOUNT_ID"/insights
  Params:  {'fields': u'date_start,campaign_id,spend', 'level': u'campaign', 'time_range': '{"since":"2018-05-02","until":"2018-05-02"}', 'time_increment': 1}
```
I am doing the request using the ```get_insights ``` method from the ``AdAccount `` object and this account has around 100 campaigns. 

Is this expected behavior?

Thanks

**Comment by shootingsyh** [comment]
@luklss can you help try the same call in graph explorer: https://developers.facebook.com/tools/explorer/ ? 
Normally this error is reported from API layer rather than SDK layer. If you see same error when trying in graph explorer, try to further reduce the amount of data or report the issue in bug tool.
If graph explorer works but SDK not, reopen this issue. 
Thanks.

**Comment by luklss** [comment]
Thanks @shootingsyh 
I did manage to solve with the API support. 
If anyone had the same issue, refer to:
https://developers.facebook.com/support/bugs/194282471371172/
