### ISSUE TITLE
page create_page_backed_instagram_account fails for not using the Page Access token

### ISSUE THREAD

**Issue by dadoeyad** [facebook/facebook-python-business-sdk#517]
Ass mentioned in the documentation https://developers.facebook.com/docs/graph-api/reference/page/page_backed_instagram_accounts/ this endpoint needs to be called with the page access token. So the call `create_page_backed_instagram_account` fails for not using the page access token.

**Comment by jingping2015** [comment]
What's the issue here ? I think this endpoint need page access token and will not work for other access token.

**Comment by jingping2015** [comment]
Since we want to handle bugs more efficiently, we've decided to close issue reporting in Github and move to our dedicated bug reporting channel. If you encounter a bug with Business SDK (Python), please report the issue at [our developer bug reporting channel](https://developers.facebook.com/support/bugs/).
