### ISSUE TITLE
AdCreative with video cannot be created using image_url field within video_data

### ISSUE THREAD

**Issue by evanthomas1** [facebook/facebook-python-business-sdk#518]
Cannot create AdCreative for video ad when thumbnail is specified in object_story_spec.video_data.image_url rather than in object_story_spec.video_data.image_hash. Additionally, misleading error message is returned. Error message and AdCreative structure have been provided for reference.
<img width="852" alt="ad_creative_bug" src="https://user-images.githubusercontent.com/38570598/44880288-0f734400-ac7a-11e8-8333-f02493f49b1a.png">
<img width="842" alt="screen shot 2018-08-30 at 5 29 38 pm" src="https://user-images.githubusercontent.com/38570598/44880628-08990100-ac7b-11e8-8d46-437db85df472.png">

**Comment by evanthomas1** [comment]
Note that I have made the exact same request substituting image_hash for image_url with a hash from our Image library supplied to image_hash and the request goes through as expected.

**Comment by jingping2015** [comment]
Can you provide the call you made to get this error ?

**Comment by jingping2015** [comment]
Since we want to handle bugs more efficiently, we've decided to close issue reporting in Github and move to our dedicated bug reporting channel. If you encounter a bug with Business SDK (Python), please report the issue at [our developer bug reporting channel](https://developers.facebook.com/support/bugs/).
