### ISSUE TITLE
could not find cost per result, mobile app purchases conversion value in the api campaigns Insights

### ISSUE THREAD

**Issue by qJerry** [facebook/facebook-python-business-sdk#530]
i want to get some mesg from ads api, but i could not find cost per result, mobile app purchases conversion value in the api campaigns Insights, pls help me to solve this problem!

**Comment by jingping2015** [comment]
Since we want to handle bugs more efficiently, we've decided to close issue reporting in Github and move to our dedicated bug reporting channel. If you encounter a bug with Business SDK (Python), please report the issue at [our developer bug reporting channel](https://developers.facebook.com/support/bugs/).
