### ISSUE TITLE
_setitem_trigger was moved outside class AdCreative

### ISSUE THREAD

**Issue by redfloweret** [facebook/facebook-python-business-sdk#532]
Hi! 
this "Auto-generated python SDK code update"
https://github.com/facebook/facebook-python-business-sdk/commit/456ebfa8389f1968fe9f511dd058da7b21a4de51#diff-47ae67801add0c764a0c92f0dc703569
in `facebook_business/adobjects/adcreative.py`
moves method  `_setitem_trigger` outside class `AdCreative`.
It seems wrong, could you move it back?

**Comment by jingping2015** [comment]
Since we want to handle bugs more efficiently, we've decided to close issue reporting in Github and move to our dedicated bug reporting channel. If you encounter a bug with Business SDK (Python), please report the issue at [our developer bug reporting channel](https://developers.facebook.com/support/bugs/).
